name: Publish

on:
  workflow_dispatch:
  release:
    types:
      - published 

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Get Version
      uses: kzrnm/get-net-sdk-project-versions-action@v1.3.0
      id: get-version
      with:
        proj-path: src/OneWare.NetlistSvg/OneWare.NetlistSvg.csproj
    - name: Build
      run: dotnet build src/OneWare.NetlistSvg/OneWare.NetlistSvg.csproj -c Release -o publish
    - name: Compress
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: ../OneWare_NetlistSvgExtension_${{steps.get-version.outputs.version}}_all.zip
        directory: ./publish
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "OneWare_NetlistSvgExtension_${{steps.get-version.outputs.version}}_all.zip"
        tag: ${{steps.get-version.outputs.version}}
        allowUpdates: true
